<!--
    Tura - Application generation solution

    Copyright 2008-2026 2182342 Ontario Inc ( arseniy.isakov@turasolutions.com )

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>org.tura.model-designer</groupId>
	<artifactId>model-designer-parent</artifactId>
	<version>6.3.0</version>

	<packaging>pom</packaging>

	<name>Metamodel designer</name>
	<description>Metamodel designer</description>

	<properties>
		<wildfly-arquillian-container-managed-version>8.1.0.Final</wildfly-arquillian-container-managed-version>
		<keycloak-version>12.0.1</keycloak-version>
		<slf4j-version>1.6.1</slf4j-version>
		<tura.platform.version>${project.version}</tura.platform.version>
		<postgres.jdbc.version>42.1.1</postgres.jdbc.version>
		<version.jakartaee>10.0.0</version.jakartaee>
		<version.junit>5.11.2</version.junit>
		<version.junit-platform-suite>1.11.2</version.junit-platform-suite>
		<version.neo4j.ogm>4.0.16</version.neo4j.ogm>
	</properties>

	<dependencyManagement>
		<dependencies>

			<dependency>
				<groupId>org.neo4j</groupId>
				<artifactId>neo4j-ogm-core</artifactId>
				<version>${version.neo4j.ogm}</version>
			</dependency>

			<dependency>
				<groupId>org.neo4j</groupId>
				<artifactId>neo4j-ogm-bolt-driver</artifactId>
				<version>${version.neo4j.ogm}</version>
			</dependency>


			<dependency>
				<groupId>jakarta.platform</groupId>
				<artifactId>jakarta.jakartaee-api</artifactId>
				<version>${version.jakartaee}</version>
			</dependency>

			<dependency>
				<groupId>org.junit.jupiter</groupId>
				<artifactId>junit-jupiter-api</artifactId>
				<version>${version.junit}</version>
			</dependency>

			<dependency>
				<groupId>org.junit.platform</groupId>
				<artifactId>junit-platform-suite</artifactId>
				<version>${version.junit-platform-suite}</version>
			</dependency>


			<dependency>
				<groupId>org.tura.platform</groupId>
				<artifactId>uuiserver-commons</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.platform.repository</groupId>
				<artifactId>cdi-persistence-repo-starter-jee</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>


			<dependency>
				<groupId>org.tura.platform.repository</groupId>
				<artifactId>cdi-util</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>


			<dependency>
				<groupId>org.tura.platform.repository</groupId>
				<artifactId>cdi-rest</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.platform.repository</groupId>
				<artifactId>cdi-client-providers</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.platform.datacontrol</groupId>
				<artifactId>core</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.platform.datacontrol</groupId>
				<artifactId>annotations</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.platform.repository</groupId>
				<artifactId>cdi</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.model-designer</groupId>
				<artifactId>web-app-commons</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.platform.repository</groupId>
				<artifactId>rest-client</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.model-designer.ui</groupId>
				<artifactId>mm-navigator-interface</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.model-designer.ui</groupId>
				<artifactId>mm-tree-selection-interface</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>


			<dependency>
				<groupId>org.tura.model-designer.ui</groupId>
				<artifactId>mm-properties-interface</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.model-designer.ui</groupId>
				<artifactId>mm-frame-interface</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.model-designer.ui</groupId>
				<artifactId>mm-mapper-interface</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.model-designer.ui</groupId>
				<artifactId>mm-types-interface</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>


			<dependency>
				<groupId>org.tura.model-designer.ui</groupId>
				<artifactId>mm-technologies-interface</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>
			<dependency>
				<groupId>org.tura.model-designer.ui</groupId>
				<artifactId>mm-messages-interface</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.model-designer.ui</groupId>
				<artifactId>mm-artifacts-interface</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.model-designer.ui</groupId>
				<artifactId>mm-styles-interface</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.model-designer.ui</groupId>
				<artifactId>mm-recipe-interface</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>


			<dependency>
				<groupId>org.tura.cli.metamodel.tura-model</groupId>
				<artifactId>tura-neo4j-model-command</artifactId>
				<version>${project.version}</version>
			</dependency>


			<dependency>
				<groupId>org.tura.cli.metamodel.tura-model</groupId>
				<artifactId>model</artifactId>
				<version>${project.version}</version>
			</dependency>


			<dependency>
				<groupId>org.tura.model-designer.repository</groupId>
				<artifactId>persistence-repository-neo4j</artifactId>
				<version>${project.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.model-designer.repository</groupId>
				<artifactId>domain-persistence-repository</artifactId>
				<version>${project.version}</version>
			</dependency>


			<dependency>
				<groupId>org.tura.model-designer.repository</groupId>
				<artifactId>metamodel-repository-proxy</artifactId>
				<version>${project.version}</version>
			</dependency>


		</dependencies>

	</dependencyManagement>


	<profiles>
		<profile>
			<id>Build</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<modules>
				<module>mm-object-repository</module>
				<module>web-app-commons</module>
				<module>mm-frame-triggers</module>
				<module>mm-navigator-triggers</module>
				<module>mm-messages-triggers</module>
				<module>mm-technologies-triggers</module>
				<module>mm-artifacts-triggers</module>
				<module>mm-styles-triggers</module>
				<module>mm-tree-selection-triggers</module>
				<module>mm-mapper-triggers</module>
				<module>mm-recipe-triggers</module>
				<module>mm-types-triggers</module>
				<module>mm-properties-triggers</module>
			</modules>
		</profile>
		<profile>
			<id>Testing</id>
			<modules>
				<module>integration-testing</module>
			</modules>
		</profile>
	</profiles>


	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
		</plugins>

	</build>


</project>
