<?xml version="1.0" encoding="UTF-8"?>
<!--
      Tura - Application generation solution

      Copyright (C) 2008-2026 2182342 Ontario Inc ( arseniy.isakov@turasolutions.com ).


      This project includes software developed by Arseniy Isakov
      https://github.com/isakovarseniy/tura
      All rights reserved. This program and the accompanying materials
      are made available under the terms of the Eclipse Public License v2.0
      which accompanies this distribution, and is available at
      http://www.eclipse.org/legal/epl-v20.html
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>


	<parent>
	    <groupId>org.tura.cli</groupId>
	    <artifactId>metamodel</artifactId>
		<version>6.3.0</version>
	</parent>	

	<groupId>org.tura.cli.metamodel</groupId>
	<artifactId>commons-model</artifactId>
	
	<name>Tura :: Platform :: Processor :: Tura :: Metamodel :: Commons Model </name>
	
	
	<packaging>jar</packaging>

	<dependencies>
		<dependency>
		  <groupId>org.tura.cli</groupId>
	      <artifactId>cli-tura-command-api</artifactId>
		</dependency>

		<dependency>
			<groupId>commons-lang</groupId>
			<artifactId>commons-lang</artifactId>
		</dependency>

		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
		</dependency>

		<dependency>
			<groupId>org.tura.cli</groupId>
			<artifactId>cli-tura-command-api</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>org.eclipse.epsilon</groupId>
			<artifactId>org.eclipse.epsilon.egl.engine</artifactId>
		</dependency>


		<dependency>
			<groupId>org.eclipse.epsilon</groupId>
			<artifactId>org.eclipse.epsilon.evl.engine</artifactId>
		</dependency>

		<dependency>
			<groupId>org.eclipse.epsilon</groupId>
			<artifactId>org.eclipse.epsilon.common</artifactId>
		</dependency>

		<dependency>
			<groupId>com.google.googlejavaformat</groupId>
			<artifactId>google-java-format</artifactId>
		</dependency>

		<dependency>
			<groupId>com.github.javaparser</groupId>
			<artifactId>javaparser-core</artifactId>
		</dependency>

		<dependency>
			<groupId>org.eclipse.epsilon</groupId>
			<artifactId>org.eclipse.epsilon.eol.engine</artifactId>
		</dependency>

		<dependency>
			<groupId>org.freemarker</groupId>
			<artifactId>freemarker</artifactId>
		</dependency>	

		<dependency>
			<groupId>org.tura.cli</groupId>
			<artifactId>cli-tura-commons</artifactId>
		</dependency>


	</dependencies>


</project>
