<!--
    Tura - Application generation solution

    Copyright 2008-2024 2182342 Ontario Inc ( arseniy.isakov@turasolutions.com )

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>org.tura.model-designer</groupId>
	<artifactId>model-designer-parent</artifactId>
	<version>6.1.2</version>

	<packaging>pom</packaging>

	<name>Metamodel designer</name>
	<description>Metamodel designer</description>

	<properties>
		<wildfly-arquillian-container-managed-version>8.1.0.Final</wildfly-arquillian-container-managed-version>
		<junit-version>4.11</junit-version>
		<javaee-api-version>7.0</javaee-api-version>
		<keycloak-version>12.0.1</keycloak-version>
		<slf4j-version>1.6.1</slf4j-version>
		<reasteasy.version>3.13.2.Final</reasteasy.version>
		<resteasy-jackson2-provider>3.0.12.Final</resteasy-jackson2-provider>
		<version.hibernate-entitymanager>5.4.0.Final</version.hibernate-entitymanager>
		<version.hibernate-jpa-2.1-api>1.0.0.Final</version.hibernate-jpa-2.1-api>
		<tura.platform.version>${project.version}</tura.platform.version>
		<version.deltaspike>1.6.1</version.deltaspike>
		<postgres.jdbc.version>42.1.1</postgres.jdbc.version>
		<version.jackson-databind>2.14.2</version.jackson-databind>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.hibernate.javax.persistence</groupId>
				<artifactId>hibernate-jpa-2.1-api</artifactId>
				<version>${version.hibernate-jpa-2.1-api}</version>
			</dependency>

			<dependency>
				<groupId>org.hibernate</groupId>
				<artifactId>hibernate-entitymanager</artifactId>
				<version>${version.hibernate-entitymanager}</version>
			</dependency>

			<dependency>
				<groupId>javax</groupId>
				<artifactId>javaee-api</artifactId>
				<version>${javaee-api-version}</version>
			</dependency>

			<dependency>
				<groupId>org.apache.deltaspike.modules</groupId>
				<artifactId>deltaspike-jpa-module-api</artifactId>
				<version>${version.deltaspike}</version>
				<scope>compile</scope>
			</dependency>

			<dependency>
				<groupId>org.apache.deltaspike.modules</groupId>
				<artifactId>deltaspike-jpa-module-impl</artifactId>
				<version>${version.deltaspike}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.platform</groupId>
				<artifactId>uuiserver-commons</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.platform.repository</groupId>
				<artifactId>cdi-persistence-repo-starter-jee</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>


			<dependency>
				<groupId>org.tura.platform.repository</groupId>
				<artifactId>cdi-util</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>


			<dependency>
				<groupId>org.tura.platform.repository</groupId>
				<artifactId>cdi-rest</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.platform.repository</groupId>
				<artifactId>cdi-client-providers</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.platform.datacontrol</groupId>
				<artifactId>core</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.platform.datacontrol</groupId>
				<artifactId>annotations</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.platform.repository</groupId>
				<artifactId>cdi</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.model-designer</groupId>
				<artifactId>web-app-commons</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.platform.repository</groupId>
				<artifactId>rest-client</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.model-designer.ui</groupId>
				<artifactId>mm-navigator-interface</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.model-designer.ui</groupId>
				<artifactId>mm-tree-selection-interface</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>


			<dependency>
				<groupId>org.tura.model-designer.ui</groupId>
				<artifactId>mm-properties-interface</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.model-designer.ui</groupId>
				<artifactId>mm-frame-interface</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.model-designer.ui</groupId>
				<artifactId>mm-mapper-interface</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.model-designer.ui</groupId>
				<artifactId>mm-types-interface</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>


			<dependency>
				<groupId>org.tura.model-designer.ui</groupId>
				<artifactId>mm-technologies-interface</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>
			<dependency>
				<groupId>org.tura.model-designer.ui</groupId>
				<artifactId>mm-messages-interface</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.model-designer.ui</groupId>
				<artifactId>mm-artifacts-interface</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.model-designer.ui</groupId>
				<artifactId>mm-styles-interface</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.model-designer.ui</groupId>
				<artifactId>mm-recipe-interface</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>


			<dependency>
				<groupId>com.fasterxml.jackson.core</groupId>
				<artifactId>jackson-databind</artifactId>
				<version>${version.jackson-databind}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.model-designer.repository</groupId>
				<artifactId>postgres-jndi-persistence-model-persistence-xml</artifactId>
				<version>${tura.platform.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.processor</groupId>
				<artifactId>processor-tura-model-command</artifactId>
				<version>${project.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.processor</groupId>
				<artifactId>processor-tura-command</artifactId>
				<version>${project.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.processor</groupId>
				<artifactId>model</artifactId>
				<version>${project.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.model-designer.repository</groupId>
				<artifactId>postgres-jdbc-persistence-model-persistence-xml</artifactId>
				<version>${project.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.model-designer.repository</groupId>
				<artifactId>persistence-repository</artifactId>
				<version>${project.version}</version>
			</dependency>

			<dependency>
				<groupId>org.tura.model-designer.repository</groupId>
				<artifactId>domain-persistence-repository</artifactId>
				<version>${project.version}</version>
			</dependency>


			<dependency>
				<groupId>org.tura.model-designer.repository</groupId>
				<artifactId>metamodel-repository-proxy</artifactId>
				<version>${project.version}</version>
			</dependency>


			<dependency>
				<groupId>org.postgresql</groupId>
				<artifactId>postgresql</artifactId>
				<version>${postgres.jdbc.version}</version>
			</dependency>

			<dependency>
				<groupId>junit</groupId>
				<artifactId>junit</artifactId>
				<version>${junit-version}</version>
			</dependency>


		</dependencies>

	</dependencyManagement>


	<profiles>
		<profile>
			<id>Build</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<modules>
				<module>mm-object-repository</module>
				<module>web-app-commons</module>
				<module>mm-frame-triggers</module>
				<module>mm-navigator-triggers</module>
				<module>mm-messages-triggers</module>
				<module>mm-technologies-triggers</module>
				<module>mm-artifacts-triggers</module>
				<module>mm-styles-triggers</module>
				<module>mm-tree-selection-triggers</module>
				<module>mm-mapper-triggers</module>
				<module>mm-recipe-triggers</module>
				<module>mm-types-triggers</module>
				<module>mm-properties-triggers</module>
			</modules>
		</profile>
		<profile>
			<id>Testing</id>
			<modules>
				<module>integration-testing</module>
			</modules>
		</profile>
	</profiles>


	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
		</plugins>

	</build>


</project>
