<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="typedefinition" nsURI="http://tura.org/2013/v1/typedefinition"
    nsPrefix="tura.typedefinition">
  <eAnnotations source="gmf"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDefinition">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//TypeElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Type" eSuperTypes="#//TypeElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//Operation" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extension" lowerBound="1"
        eType="#//TypeExtension" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeReference" eSuperTypes="#//TypeElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//reftype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeExtension">
    <eAnnotations source="gmf.link">
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="style" value="dot"/>
      <details key="width" value="2"/>
      <details key="target.decoration" value="closedarrow"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//TypeElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//TypeElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Attribute" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnValue" lowerBound="1"
        eType="#//ReturnValue" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnValue">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnValue" lowerBound="1"
        eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="reftype" instanceClassName="org.tura.metamodel.commons.types.RefType"/>
</ecore:EPackage>
