org.uberfire.ext.security.management.api.userManagementServices=KCCredentialsUserManagementService
org.uberfire.ext.security.management.keycloak.authServer=http://kc:8080/auth
org.uberfire.ext.security.management.keycloak.realm=sales-analyzer
org.uberfire.ext.security.management.keycloak.user=bpmAdmin
org.uberfire.ext.security.management.keycloak.password=qwerty
org.uberfire.ext.security.management.keycloak.clientId=kie
org.uberfire.ext.security.management.keycloak.clientSecret=5a0c1159-49f5-40fd-bce2-0f7ae8936f36