<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="domain" nsURI="http://tura.org/2013/v1/domain" nsPrefix="tura.domain">
  <eAnnotations source="gmf"/>
  <eClassifiers xsi:type="ecore:EClass" name="Domain">
    <eAnnotations source="gmf.diagram.domain"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainArtifacts" lowerBound="1"
        eType="#//DomainArtifacts" containment="true" eOpposite="#//DomainArtifacts/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainTypes" lowerBound="1"
        eType="#//DomainTypes" containment="true" eOpposite="#//DomainTypes/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainApplications" lowerBound="1"
        eType="#//DomainApplications" containment="true" eOpposite="#//DomainApplications/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainArtifacts">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="255,239,222"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Domain"
        eOpposite="#//Domain/domainArtifacts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainArtifact" upperBound="-1"
        eType="#//DomainArtifact" containment="true" eOpposite="#//DomainArtifact/parent">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainTypes">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="255,239,222"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typesrepository" eType="#//TypesRepository"
        eOpposite="#//TypesRepository/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Domain"
        eOpposite="#//Domain/domainTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainApplications">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="255,239,222"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="applications" upperBound="-1"
        eType="#//DomainApplication" containment="true" eOpposite="#//DomainApplication/parent">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Domain"
        eOpposite="#//Domain/domainApplications"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainApplication">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="241,238,203"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="application" eType="#//Application"
        eOpposite="#//Application/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//DomainApplications"
        eOpposite="#//DomainApplications/applications"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainArtifact">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//DomainArtifacts"
        eOpposite="#//DomainArtifacts/domainArtifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifact" eType="#//Artifacts"
        eOpposite="#//Artifacts/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ORMEntity" eSuperTypes="#//DomainArtifact">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="241,238,203"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JPAService" eSuperTypes="#//DomainArtifact">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="241,238,203"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EJBService" eSuperTypes="#//DomainArtifact">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="241,238,203"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artifacts">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifacts" upperBound="-1"
        eType="#//Artifact" containment="true" eOpposite="#//Artifact/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//DomainArtifact"
        eOpposite="#//DomainArtifact/artifact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artifact">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="192,192,192"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Artifacts"
        eOpposite="#//Artifacts/artifacts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configVariables" upperBound="-1"
        eType="#//ConfigVariable" containment="true" eOpposite="#//ConfigVariable/parent">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelQuery" upperBound="-1"
        eType="#//ModelQuery" containment="true" eOpposite="#//ModelQuery/parent">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specifiers" upperBound="-1"
        eType="#//Specifier" containment="true" eOpposite="#//Specifier/parent">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="template" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigVariable">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="255,225,76"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Artifact"
        eOpposite="#//Artifact/configVariables"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelQuery">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="244,255,33"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Artifact"
        eOpposite="#//Artifact/modelQuery"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//QueryParameter" containment="true" eOpposite="#//QueryParameter/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//ModelQuery"
        eOpposite="#//ModelQuery/parameters"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specifier">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="128,220,40"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Artifact"
        eOpposite="#//Artifact/specifiers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" lowerBound="1"
        upperBound="-1" eType="#//Option" containment="true" eOpposite="#//Option/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Option">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Specifier"
        eOpposite="#//Specifier/options"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Application">
    <eAnnotations source="gmf.diagram.application"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="applicationRecipes" eType="#//ApplicationRecipes"
        containment="true" eOpposite="#//ApplicationRecipes/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="applicationMappers" eType="#//ApplicationMappers"
        containment="true" eOpposite="#//ApplicationMappers/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//DomainApplication"
        eOpposite="#//DomainApplication/application"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationRecipes">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="192,192,192"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Application"
        eOpposite="#//Application/applicationRecipes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recipes" upperBound="-1"
        eType="#//ApplicationRecipe" containment="true" eOpposite="#//ApplicationRecipe/parent">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationRecipe">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="255,196,176"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recipes" eType="#//Recipes"
        eOpposite="#//Recipes/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//ApplicationRecipes"
        eOpposite="#//ApplicationRecipes/recipes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationMappers">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="164,230,255"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Application"
        eOpposite="#//Application/applicationMappers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappers" upperBound="-1"
        eType="#//ApplicationMapper" containment="true" eOpposite="#//ApplicationMapper/parent">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationMapper">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="255,237,85"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapper" eType="#//Mappers"
        eOpposite="#//Mappers/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//ApplicationMappers"
        eOpposite="#//ApplicationMappers/mappers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessObjects">
    <eAnnotations source="gmf.diagram.businessObjects"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="businessObject" upperBound="-1"
        eType="#//BusinessObject" containment="true" eOpposite="#//BusinessObject/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//BusinessPackage"
        eOpposite="#//BusinessPackage/businessobjects"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessObject">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//BusinessObjects"
        eOpposite="#//BusinessObjects/businessObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="createMethods" upperBound="-1"
        eType="#//CreateMethod" containment="true" eOpposite="#//CreateMethod/parent">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="insertMethods" upperBound="-1"
        eType="#//InsertMethod" containment="true" eOpposite="#//InsertMethod/parent">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="updateMethods" upperBound="-1"
        eType="#//UpdateMethod" containment="true" eOpposite="#//UpdateMethod/parent">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="removeMethods" upperBound="-1"
        eType="#//RemoveMethod" containment="true" eOpposite="#//RemoveMethod/parent">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="searchMethods" upperBound="-1"
        eType="#//SearchMethod" containment="true" eOpposite="#//SearchMethod/parent">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="othersMethods" upperBound="-1"
        eType="#//OtherMethod" containment="true" eOpposite="#//OtherMethod/parent">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessMethod" eSuperTypes="#//TypePointer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methodRef" eType="#//Operation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fakeMethod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateMethod" eSuperTypes="#//BusinessMethod">
    <eAnnotations source="gmf.node">
      <details key="label" value="fakeMethod"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//BusinessObject"
        eOpposite="#//BusinessObject/createMethods"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InsertMethod" eSuperTypes="#//BusinessMethod">
    <eAnnotations source="gmf.node">
      <details key="label" value="fakeMethod"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//BusinessObject"
        eOpposite="#//BusinessObject/insertMethods"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateMethod" eSuperTypes="#//BusinessMethod">
    <eAnnotations source="gmf.node">
      <details key="label" value="fakeMethod"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//BusinessObject"
        eOpposite="#//BusinessObject/updateMethods"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveMethod" eSuperTypes="#//BusinessMethod">
    <eAnnotations source="gmf.node">
      <details key="label" value="fakeMethod"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//BusinessObject"
        eOpposite="#//BusinessObject/removeMethods"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SearchMethod" eSuperTypes="#//BusinessMethod">
    <eAnnotations source="gmf.node">
      <details key="label" value="fakeMethod"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//BusinessObject"
        eOpposite="#//BusinessObject/searchMethods"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OtherMethod" eSuperTypes="#//BusinessMethod">
    <eAnnotations source="gmf.node">
      <details key="label" value="fakeMethod"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//BusinessObject"
        eOpposite="#//BusinessObject/othersMethods"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mappers">
    <eAnnotations source="gmf.diagram.mapper"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappers" upperBound="-1"
        eType="#//Mapper" containment="true" eOpposite="#//Mapper/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//ApplicationMapper"
        eOpposite="#//ApplicationMapper/mapper"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mapper" eSuperTypes="#//TypePointer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Mappers"
        eOpposite="#//Mappers/mappers"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceLayer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uiLayer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaMapper" eSuperTypes="#//Mapper">
    <eAnnotations source="gmf.node">
      <details key="label" value="fakePackageName,fakeTypeName"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mappedToPackageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mappedToClassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="artifactId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="groupId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="libraryName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Recipes">
    <eAnnotations source="gmf.diagram.recipe"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recipe" eType="#//Recipe"
        containment="true" eOpposite="#//Recipe/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurations" upperBound="-1"
        eType="#//Configuration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="infrastructures" upperBound="-1"
        eType="#//Infrastructure" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//ApplicationRecipe"
        eOpposite="#//ApplicationRecipe/recipes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UsingMappers">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappers" upperBound="-1"
        eType="#//ApplicationMapper"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PlatformLayers">
    <eLiterals name="ServiceLayer" value="1"/>
    <eLiterals name="UILayer" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Recipe" eSuperTypes="#//UsingMappers">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="255,239,222"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Recipes"
        eOpposite="#//Recipes/recipe"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ingredients" upperBound="-1"
        eType="#//Ingredient" containment="true" eOpposite="#//Ingredient/parent">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="infrastructures" upperBound="-1"
        eType="#//Infrastructure" eOpposite="#//Infrastructure/recipe">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ingredient" eSuperTypes="#//UsingMappers">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="255,222,32"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Recipe"
        eOpposite="#//Recipe/ingredients"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layer" eType="#//PlatformLayers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappers" upperBound="-1"
        eType="#//ModelMapper" containment="true" eOpposite="#//ModelMapper/parent">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="buildScript" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deployScript" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="componentRoot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaComponent" eSuperTypes="#//Component">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="128,128,128"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="artifactId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="groupId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="basePackage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Infrastructure">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="255,239,222"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recipe" eType="#//Recipe"
        eOpposite="#//Recipe/infrastructures"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="recipeConfig" eType="#//Configuration"
        eOpposite="#//Configuration/infrastructure">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="255,239,222"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="infrastructure" eType="#//Infrastructure"
        eOpposite="#//Infrastructure/recipeConfig"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="layout" value="list"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configExtension" eType="#//Configuration"
        eOpposite="#//Configuration/parent">
      <eAnnotations source="gmf.link">
        <details key="style" value="dot"/>
        <details key="width" value="2"/>
        <details key="target.decoration" value="closedarrow"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Configuration"
        eOpposite="#//Configuration/configExtension"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelMapper" eSuperTypes="#//ArtifactRef">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="192,192,192"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Component"
        eOpposite="#//Component/mappers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specifiers" upperBound="-1"
        eType="#//MappingSpecifier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="queries" upperBound="-1"
        eType="#//Query" containment="true">
      <eAnnotations source="gmf.compartment">
        <details key="layout" value="list"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eAnnotations source="gmf.node">
      <details key="label" value="fakeName"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="255,239,222"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="confVarRef" eType="#//ConfigVariable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fakeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingSpecifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specifierRef" eType="#//Specifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueRef" eType="#//Option"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Query">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="241,238,203"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelQuery" eType="#//ModelQuery"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="queryRef" eType="#//ModelQuery"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//QueryVariable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryVariable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="queryParamRef" eType="#//QueryParameter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArtifactRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainArtifactRef" eType="#//DomainArtifact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artifactRef" eType="#//Artifact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypePointer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packageRef" eType="#//Package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeRef" eType="#//TypeElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fakePackageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fakeTypeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDefinition">
    <eAnnotations source="gmf.diagram.typedefinition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//TypeElement" containment="true" eOpposite="#//TypeElement/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Package"
        eOpposite="#//Package/typedefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//TypeDefinition"
        eOpposite="#//TypeDefinition/types"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Primitive" eSuperTypes="#//TypeElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" eSuperTypes="#//TypeElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true" eOpposite="#//Attribute/parent">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//Operation" containment="true" eOpposite="#//Operation/parent">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extension" upperBound="-1"
        eType="#//TypeExtension" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeReference" eSuperTypes="#//TypeElement #//TypePointer">
    <eAnnotations source="gmf.node">
      <details key="label" value="fakePackageName,fakeTypeName"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeExtension">
    <eAnnotations source="gmf.link">
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="style" value="dot"/>
      <details key="width" value="2"/>
      <details key="target.decoration" value="closedarrow"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//TypeElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//TypeElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//TypePointer">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Type"
        eOpposite="#//Type/attributes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Type"
        eOpposite="#//Type/operations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true" eOpposite="#//Parameter/parent">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnValue" eType="#//ReturnValue"
        containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//TypePointer">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Operation"
        eOpposite="#//Operation/parameters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnValue" eSuperTypes="#//TypePointer">
    <eAnnotations source="gmf.node">
      <details key="label" value="fakePackageName,fakeTypeName"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enumarator" eSuperTypes="#//TypeElement">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//EnumAttribute" containment="true" eOpposite="#//EnumAttribute/parent">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumAttribute">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Enumarator"
        eOpposite="#//Enumarator/values"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypesRepository">
    <eAnnotations source="gmf.diagram.typesrepository"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeDefinition" lowerBound="1"
        eType="#//Types" containment="true" eOpposite="#//Types/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//DomainTypes"
        eOpposite="#//DomainTypes/typesrepository"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Types">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="255,239,222"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//TypesRepository"
        eOpposite="#//TypesRepository/typeDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="#//Package" containment="true" eOpposite="#//Package/parent">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="businessPackages" upperBound="-1"
        eType="#//BusinessPackage" containment="true" eOpposite="#//BusinessPackage/parent">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.color" value="0,0,0"/>
      <details key="color" value="241,238,203"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typedefinition" eType="#//TypeDefinition"
        eOpposite="#//TypeDefinition/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Types"
        eOpposite="#//Types/packages"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessPackage">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="businessobjects" eType="#//BusinessObjects"
        eOpposite="#//BusinessObjects/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Types"
        eOpposite="#//Types/businessPackages"/>
  </eClassifiers>
</ecore:EPackage>
