//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.07 at 03:41:43 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tura.org/platform/hutn/workflow", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.tura.platform.hutn.workflow;
