<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tura" nsURI="http://tura.org/2016/v2/tura" nsPrefix="tura">
  <eSubpackages name="domain" nsURI="http://tura.org/2016/v2/domain" nsPrefix="tura.domain">
    <eClassifiers xsi:type="ecore:EClass" name="Domain">
      <eAnnotations source="gmf.diagram"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="domainArtifacts" lowerBound="1"
          eType="#//domain/DomainArtifacts" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="domainTypes" lowerBound="1"
          eType="#//domain/DomainTypes" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="domainApplications" lowerBound="1"
          eType="#//domain/DomainApplications" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DomainArtifacts">
      <eAnnotations source="gmf.node">
        <details key="label" value="name"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="domainArtifact" upperBound="-1"
          eType="#//domain/DomainArtifact" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DomainArtifact">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="artifact" eType="ecore:EClass artifact.ecore#//Artifact"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DomainTypes">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typesRepository" upperBound="-1"
          eType="#//domain/DomainTypesRepository" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DomainTypesRepository">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="repository" eType="ecore:EClass type.ecore#//Repository"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DomainApplications">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="applications" upperBound="-1"
          eType="#//domain/DomainApplication" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DomainApplication">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="application" eType="ecore:EClass application.ecore#//Application"
          containment="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
