<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="objectmapper" nsURI="http://tura.org/2016/v2/objectmapper" nsPrefix="tura.objectmapper">
  <eClassifiers xsi:type="ecore:EClass" name="ProcessingStage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextStage" eType="#//ProcessingStage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectMapperGroup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectMappers" upperBound="-1"
        eType="#//ObjectMapper" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stages" upperBound="-1"
        eType="#//ProcessingStage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributesConnector" upperBound="-1"
        eType="#//AttributeConnector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationsConnector" upperBound="-1"
        eType="#//OperationConnector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//Variable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectMapper" eSuperTypes="artifact.ecore#//Categorized">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stage" eType="#//ProcessingStage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseType" eType="ecore:EClass type.ecore#//TypePointer"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
        eType="#//OmRelation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calculations" upperBound="-1"
        eType="#//CalculatedField" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggrigations" upperBound="-1"
        eType="#//Aggregation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="ecore:EClass type.ecore#//AttributePointer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//CalculatedField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aggregation" eSuperTypes="#//CalculatedField"/>
  <eClassifiers xsi:type="ecore:EClass" name="OmRelation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectMapperRef" eType="#//ObjectMapper"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeRef" eType="ecore:EClass type.ecore#//TypeElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assosiationRef" eType="ecore:EClass type.ecore#//Assosiation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationConnectorRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationRef" eType="#//OperationConnector"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeConnector" eSuperTypes="#//OperationConnectorRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mergeAttr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultSearch" eType="ecore:EClass form.ecore#//ContextParameters"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationConnector" eSuperTypes="#//OperationConnectorRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//ObjectMapper"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//ObjectMapper"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationType" eType="#//OperationType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultSearch" eType="ecore:EClass form.ecore#//ContextParameters"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperationType">
    <eLiterals name="mergeOrAdd"/>
    <eLiterals name="add" value="1"/>
    <eLiterals name="delete" value="2"/>
    <eLiterals name="non" value="3"/>
    <eLiterals name="oneTimes" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CalculatedField" eSuperTypes="type.ecore#//TypePointer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
